[workspace]
resolver = "2"
members = ["crates/codeindex", "crates/codeindex_common", "crates/qdrant"]

[patch.crates-io]
# Temporary patch until <https://github.com/hyperium/tonic/pull/1401> is merged
tonic = { git = 'https://github.com/qdrant/tonic', branch = "v0.9.2-patched" }
